services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-nestjs_basecode}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"

volumes:
  postgres_data:
